new login logic, linux port, improved robustness, logging with tracing, etc.
ArcticLampyrid/njupt_wifi_login pull request #2
Opened 2023-04-02 13:18 UTC by NKID00

- brand new login logic that checks login status beforehand and after
- linux port utilizing rtnetlink
- retry for three times and debounce to improved robustness
- introduce crate tracing to handle logging

Tested both on Kubuntu GNU/Linux 22.04.2 (Kernel 5.15.0) and Windows 10 21H2 (19044.2728).

2023-04-02 13:21 UTC, NKID00 commented
DNS resolver is removed because accessing IP directly seems to works fine enough.

2023-04-03 01:05 UTC, ArcticLampyrid requested changes

2023-04-03 01:05 UTC, ArcticLampyrid commented on .gitignore
> +.vscode
why? I believe we should provide a out-of-box development environment.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/login.rs
> +const URL_BASE: &str = "http://10.10.244.11";
Actually I do not think a hard-encoded ip is suitable.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/login.rs
> +        .text_with_charset("GBK")
I'm wondering whether this will require extra dependencies or system components.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/login.rs
> +        .await?
If we connect to any AP other than NJUPT's, we will get an error. This may be not a good design.
Personally, I often connect to my mobile hotspot after 11.30p.m.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/main.rs
> +pub struct Credential {
There can be additional options aside from credentials. Define a separated struct and put it into Config struct with "flatten" attr.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/main.rs
> +            info!("Start to login (try {try_count}/{MAX_TRY_COUNT})");
Perhaps we need to delay before a next attempt.
BTW, it's intended failed when it's not in the working time. Can we differentiate it?

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/login.rs
> +    "/eportal/?c=ACSetting&a=Login&wlanuserip={}&wlanacip=10.255.252.150&&wlanacname=XL-BRAS-SR8806-X"
A hard-encoded acip and acname can be dangerous. Is there any significant reason to do so?

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/network_changed/linux.rs
> +impl Drop for NetworkChangedListener {
It can be curious that when the caller decided to delete a listener, both closing a channel and dropping the object is needed.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/main.rs
> +    while let Some(()) = rx.recv().await {
We may have other actions than "Login" in the main event loop. Eg. I'm going to add a IPv6 Guard, this may require a "ReNew6" action.

2023-04-03 01:05 UTC, ArcticLampyrid commented on core/src/network_changed/linux.rs
> +            while let Some((message, _)) = messages.next().await {
In Windows implementation, there is a initial message. Is it the same as Linux implementation?

2023-06-01 16:12 UTC, ArcticLampyrid commented on core/src/login.rs
> +        .await?
**ATTENTION**
Unconditional attempt to connect to NJUPT may leave identity characteristics in the public network, which may lead to security risks. 
Even the old logic is risky (see #3), but at least it requires the attacker to construct a special network, which cannot be analysed only via normal log file.

2023-07-02 05:49 UTC, ArcticLampyrid commented on core/src/login.rs
> +    "/eportal/?c=ACSetting&a=Login&wlanuserip={}&wlanacip=10.255.252.150&&wlanacname=XL-BRAS-SR8806-X"
This is not correct for SPL（三牌楼） area.

2024-02-07 17:20 UTC, ArcticLampyrid commented
Closed as it's out-dated.
Some code like Linux ports were manually merged into the mainline.

2024-02-07 17:20 UTC, closed without merging